-- the following tables define what questions the Konstapeln ("OFC") will ask / what orders the Konstapeln will give / what information the Konstapeln conveys.
-- the answers of the ped ("Normal") are defined as well.
NormalAddress = {'Hej Konstapeln.', 'Hur står det till?'}
NormalGreetResponse = NormalAddress
NormalLicenceResponse = {'Ja visst.', 'Ja visst konstapeln.'}
NormalLicenceHideResponse = {"Jag måste ha glömt det hemma", "Hmm... Det måste ju vara här nånstans", "Jag har tappat bort det."}
NormalNoLicenceResponse = {"Jag äger inget.", "Jag har inget"}
NormalNoDrugResponse = {"Nej, jag använder inte droger.", "Nej, konstapeln, det är ju olagligt.", "Självklart inte."}
NormalDrugResponse = {"N.n.Narkotika? N.n.nej.", "Jag är fan helt maxad."}
NormalNoAlcoholResponse = {"Nej, Jag har inte druckit alkohol.", "Nej."}
NormalAlcoholHideResponse = NormalNoAlcoholResponse
NormalAlcoholResponse = {"Ja, Jag drack ett glas vin till maten.", "Jag kan ha tagit en jävel för mycket...", "Ja, men det är väl inte olagligt?"}
NormalNoIllegalItemsResponse = {"Nej, Konstapeln.", "Självklart inte.", "Jag har inget olagligt."}
NormalIllegalItemsResponse = {"Jag hittade faktiskt det här förut...", "Olagliga föremål? nejnej..."}
NormalIllegalItemsHideResponse = NormalNoIllegalItemsResponse
NormalNoWeaponsResponse = {"Jag är obeväpnad.", "Nej, Konstapeln.", "Jag har inga vapen på mig."}
NormalWeaponsResponse = {"Ja, Jag är ett vapen med mig.", "Jag är beväpnad.", "Ja, konstapeln.", "Ja, Jag hittade ett vapen...", "Ja, men det är helt lugnt."}
NormalWeaponsHideResponse = NormalNoWeaponsResponse
NormalIllegalWeaponsResponse = NormalWeaponsResponse
NormalIllegalWeaponsHideResponse = NormalNoWeaponsResponse
NormalAnswerStartingPoint = {"Jag åkte hemifrån.", "Jag är påväg hem ifrån jobbet.", "Jag är påväg hem ifrån klubben.", "Jag hade ett bankärende.", "Jag har handlat mat.", "Bara ute och glider.", "Jag blev släppt från kåken precis.", "Jag har varit på polisstationen.", "Jag har varit hemma."}
NormalAnswerDestination = {"Jag är påväg hem.", "Jag är påväg till jobbet.", "Jag ska hämta pizza.", "Inget särskillt.", "Jag ska till din mamma.", "Jag ska handla mat.", "Jag ska till banken.", "Jag ska till polisstationen."}
NormalAnswerActivity = {"I'm walking here!", "I'm just walking.", "Standing around, doing nothing.", "Just wandering around aimlessly.", "To be honest, I don't really know..."}
NormalAnswerNoSuspiciousActivity = {"Jag har inte sätt något.", "Nej, konstapeln, inget märkvärdigt här.", "Inget utom det vanliga."}
NormalNoVehicleResponse = {"Konstapeln, det finns inget fordon.", "Konstapeln, Jag äger inget fordon.", "Vilket fordon?", "Konstapeln, är du galen? Det finns inget fordon..."}
NormalAcceptOrderResponse = {"Ja, Konstapeln.", "Okej, Konstapeln.", "Jag förstår.", "Ja visst."}
NormalRefuseOrderResponse = {"Nej, Konstapeln.", "Nej.", "Det händer inte, Konstapeln.", "Jag vägrar."}
NormalRefuseQuestionResponse = {"Det behöver du inte veta.", "Det ska du ta och skita i.", "Det säger jag inte.", "Det vill jag inte säga.", "Det kommer jag inte berätta för dig."}
NormalResistActionResponse = {"Rör mig inte!", "Du får inte göra så här!", "Rör mig inte förfan!", "Backa snutjävel!"}
NormalStopInteractionResponse = {"Konstapeln, jag vill inte prata med dig. hejdå."}
NormalFleeResponse = {"Sluta följa efter mig, Konstapeln!"}
NormalFightResponse = {"Du kommer att få smaka!"}
NormalWaitResponse = {'Snälla skynda dig.', "Okej, jag väntar.", 'Okej, Konstapeln.'}
NormalGoodbye = {'Ses igen.', 'Hej då.', 'Ha en bra dag.', 'Goddag, Konstapeln.', 'Ha en fortsatt trevlig dag.'}

OFCAskForID = {'Får jag se ditt lägg?', 'Visa mig dill lägg.', 'Jag vill se ditt lägg.', 'Har du något legitimation på dig?'}
OFCAskForDriverLicence = {"Får jag se ditt körkort?", "Visa mig ditt körkort.", "Ge mig ditt körkort.", "Har du något körkort med dig?"}
OFCAskForGunLicence = {"Får jag se din vapenlicens?", "Visa mig din vapenlicens .", "Ge mig din vapenlicens.", "Har du någon vapenlicens med dig?"}
OFCAskForSubstance = {"Har du tagit någon narkotika?", "Använder du droger?"}
OFCAskForAlcohol = {"Har du druckit alkohol?", "Har du druckit alkohol idag?", "Är du alkoholpåvärkad?"}
OFCAskForIllegalItems = {"Har du något olagligt på dig?", "Har du något på dig som du inte bör ha?"}
OFCAskForWeapons = {"Bär du skjutvapen?", "Är du beväpnad?", "Bär du på några vapen?"}
OFCAskForStartingPoint = {"Vart har du varit?"}
OFCAskForDestination = {"Vart ska du?"}
OFCAskForActivity = {"Vad ska du göra nu?"}
OFCAskForSuspiciousActivity = {"Sett något suspekt?"}
OFCOrderOutOfVehicle = {"Var snäll att gå ur fordonet.", "Gå ut ur fordonet NU!", "Gå ut ur fordonet."}
OFCOrderIntoVehicle = {"Var snäll och sätt dig i fordonet.", "Sätt dig i fordonet NU!", "Sätt dig i fordonet igen."}
OFCInformBreathalyzer = {"Var snäll och blås tills det klickar.", "Jag skulle vilja att du blåser i den här.", "Var snäll och blås tills det klickar."}
OFCInformDrugtest = {"Jag kommer göra ett drogtest på dig.", "Jag kommer testa dig på narkotika."}
OFCInformPersonSearch = {"Jag ska visitera dig.", "Jag skulle vilja kolla i dina fickor. Har du något som jag kan skada mig på?", "Jag kommer göra en kroppsvisitation på dig."}
OFCInformCarSearch = {"Jag kommer söka igenom ditt fordon.", "Var snäll och öppna fordonet så jag kan kolla."}
OFCInformCarSeizure = {"Jag måste ta din bil.", "Du får inte köra detta fordon längre.", "Jag tar fordonet."}
OFCInformObjectConfiscation = {"Jag måste ta detta föremål ifrån dig.", "Jag konfiskerar detta föremål."}
OFCInformArrest = {"Du ska med till station för vidare förhör.", "Var snäll och vänd dig om."}
OFCInformFine = {"Jag kommer skriva en böter på det här.", "Jag måste ge dig en böter."}

OFCWait = {"Var snäll och vänta, Jag kommer tillbaka.", "Vänta här är du snäll.", "var snäll och håll dig här, så kommer jag snart."}
OFCBye = {'Ha en bra dag.', 'Okej, du kan åka.', 'Hej Då.', 'Försvinn.', 'Vi ses.'}